### ISSUE TITLE
Problem installing mitoVGP_conda_env_ONT.yml

### ISSUE THREAD

**Issue by gitcruz** [gf777/mitoVGP#2] opened 2021-08-30 16:29 UTC
Hi Giulio,

I have just followed the instructions provided and installed canu & mitoVGP_conda_env_ONT.yml without any problem.
However when I try conda env create -f mitoVGP_conda_env_ONT.yml I get the following error

_Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - gcc_impl_linux-64==7.3.0=habb00fd_2_

I am not sure if the problem is on the repository side or in the modules i am loading to use conda (gcc/6.3.0 mkl/11.3.3 PYTHON/3.7.1 CONDA/4.5.11_PYTHON3).

Thanks for developing this and congrats for the publication!
Fernando

**Comment by gitcruz** [comment] 2021-09-01 15:44
Hi,

I just tried with other two conda versions CONDA/4.3.11_PYTHON3 & CONDA/4.10.1_PYTHON3.8 and I still get same error Solving the environment.

Do you have any idea on how to overcome this problem?

Thanks,
Fernando

**Comment by mcurto** [comment] 2021-11-08 18:49
Hi,
I am having the same problem. Did someone find a solution in the meanwhile?
Thanks,
Manuel

**Comment by Soniazumalave** [comment] 2021-11-19 12:15
Hi, 
Same problem here! Any solution? 
Many thanks, 
Sonia

**Comment by gitcruz** [comment] 2021-11-19 15:59
Sorry I haven't. I tried editing  replacing the original gcc
(gcc_impl_linux-64=7.3.0=habb00fd_2) for a the local one in our cluster
(gcc_impl_linux-64=7.3.0=hd420e75_5) in the mitoVGP_conda_env_ONT.yml.
However, when i recreated the conda environment I  have ran in many
conflicts with most of the programs in the environment, for example:









*Package whatshap conflicts for:medaka==0.11.0=py36hbcae180_0 ->
whatshap==0.18whatshap==0.18=py36h6bb024c_0The following specifications
were found to be incompatible with your system:   -
feature:/linux-64::__glibc==2.12=0  - feature:|@/linux-64::__glibc==2.12=0
- bcftools==1.9=h68d8f2e_9 -> libgcc-ng[version='>=7.3.0'] ->
__glibc[version='>=2.17']  - binutils_impl_linux-64==2.33.1=he1b5a44_7 ->
libgcc-ng[version='>=7'] -> __glibc[version='>=2.17']  -
biopython==1.74=py36h516909a_0 -> libgcc-ng[version='>=7.3.0'] ->
__glibc[version='>=2.17']*

So it's even worse.

Please let me know if you find a solution.

Best,
Fernando

**Comment by DustinSokolowski** [comment] 2021-12-17 18:51
Hey!

I just wanted to update to say that I am having the same problem as well.

The problem is that the version of GCC is broken:
![image](https://user-images.githubusercontent.com/56414662/146594753-d74a7750-058f-4ed6-b985-185ce273fd78.png)

There are multiple other gcc 7.3's that are functional as Fernando mentioned.
![image](https://user-images.githubusercontent.com/56414662/146594848-22e8d87d-1d3e-44bf-b4aa-c408afc8ccbd.png)

Given that it did not work for him when he tried to replace the GCC's, it may be possible that Giulio @gf777 may need to update mitoVGP with the appropriate version of gcc and make sure that everything is cross-compatible.

Thanks!
Dustin

**Comment by DustinSokolowski** [comment] 2021-12-17 20:09
Quick update, I tried to update the version of gcc in the xml file as well as well as remove that package altogether and I had a massive number of conflicts as well.

To make sure it's not a conda version on my end I was able to create the pacbio environment without any issues.

Best!
Dustin

**Comment by gf777** [comment] 2021-12-17 20:27
Hi everyone,

sorry for some reason git wasn't sending me updates on this topic and I didn't realize so many of you were experiencing this problem. Indeed the ONT env wasn't highly tested as we work mostly with CLR data. Assuming you are all having problems with the ONT environment, I'll try to reinstall it myself and get back to you.

Sorry for the inconvenience.

Giulio

**Comment by DustinSokolowski** [comment] 2021-12-17 20:36
Hey Giulio,

Thank you so much for the quick reply and I really appreciate it! I've follow the VGP pipeline to get a very nice looking _de novo_ genome so I'm looking forward to mitoVGP being compatible with nanopore data again and having a high-confident mt genome as well.

Best!
Dustin

**Comment by gf777** [comment] 2021-12-17 22:04
Hello folks @gitcruz @mcurto @Soniazumalave @DustinSokolowski 

Basically the conda package for gcc 7.3 was not available anymore and I replaced it with https://anaconda.org/ehmoussi/gcc_impl_linux-64

Sorry for this, I fixed the ONT environment and I am able to install it.

Please let me know if this fixes the issue. Sorry for the late follow up!

Giulio

**Comment by DustinSokolowski** [comment] 2021-12-17 23:28
Thank you again for doing this. I can activate the conda environment successfully. I'll let you know about running jobs before closing the issue.

Best,
Dustin

**Comment by gf777** [comment] 2021-12-18 03:41
Cool. I also run the pipeline on a previous ONT test dataset and it works just fine, but obviously success will depend on the dataset(s) and params.

Giulio

**Comment by DustinSokolowski** [comment] 2021-12-28 00:45
Hey Giulio,

Thank you for your patience in me getting back to you and happy holidays! While it does run for the first little while, I think that there may be an error with using nanopore and 10X linked reads that are on my local machine.

Command:

`mitoVGP -a ONT -s heterocephalus_glaber -i hGlab -r /refpath/HetGla_fem_MT.fa -t 24 -1 /aln_nano_path/NMR_male_to_hetgla_aligned_MT.bam -2 /10X_path/WL3056_SUB2626M_S1_L001_R1_001.fastq.gz /10X_path/WL3056_SUB2626M_S1_L001_R2_001.fastq.gz > take1.txt`

Note: if I do not pipe the command into something then my computer crashes.

The reason I think that my computer is crashing is because this command actually _prints the bam file into all of the logs_ instead of saving them somewhere. 

I'm 99% sure that the error is that you need `echo` instead of `cat` on line 168 of `mtDNApipe`.

I have a reproducible example below:

![image](https://user-images.githubusercontent.com/56414662/147515990-ed038579-bb12-4d4f-a5eb-4ce15b89b208.png)

Hopefully this is the only issue, but if you could possibly test an example using nanopore bam and fastq files locally (as us users will be running it), then it would be a huge huge help.

Thanks so much!
Dustin

**Comment by DustinSokolowski** [comment] 2021-12-28 01:11
As a very quick followup, I think that there may be some more internal issues I'm having a tough time seeing. When I fixed the previous bug and ran it again, it looked like 20 sequences aligned to the MT genome using minimap2. This being said, when I aligned with bwa, I was able to align 37,000 reads to the MT chromosome of my reference. could this be a real intrinsic difference between the two aligners or do you think there could be another small bug in the code somewhere? Furthermore, the `hGlab.contigs.fasta` fasta file also does not exist regardless of if I use the default parameters, or the parameters suggested here (https://github.com/VGP/vgp-assembly/issues/46).

If you get the chance to test the nanopore bam file then I'd be very grateful. Otherwise, do you think that bwa is an acceptable aligner? If so I'm tempted to follow the mitoVGP pipeline but starting by building MT aligned reads with canu.

Thanks so much!
Dustin

**Comment by gf777** [comment] 2021-12-28 15:05
Hello Dustin,

you shouldn't work with a bam file with your ONT data to start with. Bam is usually for aligned reads, and even when it's used to store unaligned reads most genome tools will want them converted to fastq/fastq.gz. I am not using ONT reads very often, however I think they are also generally in fastq. So I think the pipeline is fine but you should provide fastq not bam to mitoVGP.

Wrt BWA, afaik this is a short read aligner so it's not a good choice. The whole point here is identifying true positive mt reads, as opposed to spurious matches based on short alignments or NUMTs. You should use a long read aligner for this.

All the best,

Giulio

**Comment by DustinSokolowski** [comment] 2021-12-28 19:54
Hey Giulio, 

I'm not entirely sure that I follow. The code itself looks for a file with the aligned*.bam header, and you have stated that the long read data needs to be in bam file format here: https://github.com/VGP/vgp-assembly/issues/53.

I tried what (I think) you were suggesting and got the following result: 
` ./mitoVGP -a ONT -s heterosephalus_glaber -i hGlab -r /refdir/MusMusc_MT.fa -t 24 -1 /nanoporedir/WL3052_ONT_Nanopre_SUB_M.fastq.gz -2 /10Xdir/ -f 25000 -p 5`

![image](https://user-images.githubusercontent.com/56414662/147602034-3f37af87-4181-43e2-b789-1be53db5ab56.png)

Thank you for the clarification with bwa! I see what you mean, it looks like bwa mem -x ont has been deprecated for a while and minimap2 is faster/better at this point.

Thanks again!
Dustin

**Comment by gf777** [comment] 2021-12-29 07:55
Hi Dustin,

the bam input is specific to Pacbio, because it's necessary for the Arrow polishing step (which is absent in ONT). Really no point of providing anything other than fastq.

With flags `-1` and `-2` you need to provide file lists, not paths, please check the relevant lines in the help https://github.com/gf777/mitoVGP/blob/0b12102fcbfad9b3220164ec241ae48710d5bc43/mitoVGP#L43

**Comment by DustinSokolowski** [comment] 2021-12-29 19:19
Hey Guilio,

Sorry about that I did mean to send the file. I cleaned up some of the hard-coded directories to make the code a bit easier to read and I got rid of the short read file name.

Okay that's interesting about providing the fastq file for nanopore, I was thinking about that as well. So, what I think the problem is (to my understanding) with inputting a fastq file in the -1 slot is that the scripts/mtDNApipe assumes a bam file as input for they're aligning scripts. Though upon review minimap2 doesn't necessarily need a bam file as input as far as I can tell, perhaps I can overcome this by setting my aligner to minimap2 from the default. I'll let you know how it goes!

Best,
Dustin

![image](https://user-images.githubusercontent.com/56414662/147696227-3a797448-0a88-4ead-9952-0a2229518a78.png)

Update: Looks like -m minimap needs the bam file as well. 

![image](https://user-images.githubusercontent.com/56414662/147697066-14c8f272-566d-4cdd-843c-f0e567621c3d.png)

I think that it's because of the if statement here: 
`! [[ -e "${W_URL}/tgs_bam/aligned_$(basename -- "${p%.*}").bam" ]] && ! [[ $p == *scraps* ]] && ! [[ $p == *.pbi ]] && ([[ $p == *.bam ]] || [[ $p == *.fastq ]] || [[ $p == *.fasta ]] || [[ $p == *.fa ]] || [[ $p == *.fq ]]` 

When I look into the references directory, I don't see that minimap2 has tried to index the reference file yet, which to me implies it's just skipping this section altogether. It also explains how when I had an "aligned.bam" file in `-1` I got a little further along in the script. 

I added an `[[ $p == *.fastq.gz ]]` Into that if statement hoping it would let me in

I also noticed that for minimap2 it looks like the reference files are hardcoded to be a *.fasta instead of a *.fa? While this doesn't show up in the logs anywhere I can make an error on my side. 

`minimap2 -d ${W_URL}/reference/${REF%.*}.fasta.mmi ${W_URL}/reference/${REF%.*}.fasta`

I changed the fa reference file to fasta in my input.

With these changes, sequences are mapping with minimap2! Hopefully those were all the shenanigans and I'll get out of your hair for a while.

Thanks again and happy new year!

Dustin

**Comment by DustinSokolowski** [comment] 2021-12-30 18:45
Hey!

Looks like it made it to the canu step before some memory issues that are on my end. I'm happy to either close this or keep it open until it works at which point I'll summarize all of the changes/considerations needed to make nanopore work on a different GPU machine with local data so that other users will not have the same issue. Happy either way!

Best,
Dustin

**Comment by gf777** [comment] 2021-12-30 22:57
Hello Dustin,

glad to hear your are making progress. Since the original issue was solved I'll close this thread. Feel free to open new issues. Note that I was able to reproduce a Nanopore assembly with the current code, so the code itself should be fine.

All the best,

Giulio

**Closed as completed by gf777** 2021-12-30 22:57 UTC

**Comment by gitcruz** [comment] 2022-02-07 11:04
Ciao Giulio,
A bit late but I also confirm I have successfully installed the ONT environment of mitoVGP.
Thanks!
Fernando

**Comment by gf777** [comment] 2022-02-07 13:41
glad to hear it, thanks for the feedback!
